[package]
name = "cbp-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.1.0"
async-graphql-axum = "7.1.0"
axum = "0.8.8"
reqwest = { version = "0.13.1", features = ["json"] }
tokio = { version = "1.49.0", features = ["full"] }
