[workspace]
authors = ["Peter Alexander <makeroftools@creativedevelopment.systems>"]
channels = ["conda-forge"]
name = "cbp-rust"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.92.0,<1.93"
